import {
  songs as songsSelector,
  artists as artistsSelector ,
  currentSong as currentSongSelector
} from 'routes/Songs/modules/selectors';


export const INIT_SONG_VIEW   = 'INIT_SONG_VIEW';
export const SET_CURRENT_SONG = 'SET_CURRENT_SONG';
export const HIDE_MODAL       = 'HIDE_MODAL';
export const SET_SORT         = 'SET_SORT';
export const ADD_SONG         = 'ADD_SONG';

export const MODAL_ADD_SONG = 'MODAL_ADD_SONG';


// ------------------------------------
// Action Creators
// ------------------------------------

export const hideModal = () => (dispatch, getState) => {
  return dispatch({ type: HIDE_MODAL });
}

export const setCurrentSong = (rowNumber, columnNumber, e) => (dispatch, getState) => {
  // use onCellClick to access event handler to grab correct song id
  // TODO: make pull request for onRowSelect to return custom id instead of autogenerated rowNumber
  const currentSong = e.currentTarget.attributes['data-rowid'].value;
  return dispatch({ type: SET_CURRENT_SONG, payload: currentSong });
};

export const setSort = (sortField) => (dispatch, getState) => {
  return dispatch({ type: SET_SORT, payload: sortField });
};

const nextAvailableId = (songCollection) =>
  songCollection
    .map( (song) => song.id )
    .sort( (a, b) => a - b )
    .pop() + 1;

export const addSong = (values) => (dispatch, getState) => {
  const fieldValues = getState().form.addSongForm.values;
  const availableId = nextAvailableId(getState().songs.collection);
  return dispatch({ type: ADD_SONG, payload: { ...fieldValues, ...{ id: availableId }} });
};

export const viewSong = (songValues) => (dispatch, getState) => {
  return dispatch({
    type: 'SHOW_MODAL',
    meta: {
      modalType: MODAL_ADD_SONG,
      modalView: 'view',
      modalProps: {}
    }
  });
};


export const actions = {
  addSong, hideModal, setCurrentSong, viewSong
};


// ------------------------------------
// Property Mappers
// ------------------------------------

export const isOpen = (modal) => {
  return (modal.modalType === MODAL_ADD_SONG);
};

export const getCurrentSong = (state) => {
  return currentSongSelector(state);
};

export const getVisibleSongs = (state) => {
  return songsSelector(state);
};

// ------------------------------------
// Action Handlers
// ------------------------------------

const ACTION_HANDLERS = {
  [SET_CURRENT_SONG]: (state, action) =>
    ({ ...state, currentSong: action.payload }),
  ['LOCATION_CHANGE']: (state, action) =>
    ({ ...state, currentSong: null }),
  ['SET_PAGINATION_PER_PAGE']: (state, action) =>
    ({ ...state, paginationPerPage: action.payload }),
  ['SET_PAGINATION_CURRENT']: (state, action) =>
    ({ ...state, paginationCurrent: action.payload }),
  [SET_SORT]: (state, action) =>
    ({ ...state, sortField: action.payload, sortInverse:  !state.sortInverse } )

};


// ------------------------------------
// Reducer
// ------------------------------------


const initialState = {
  currentGenres:      [],
  currentInstruments: [],
  initialized:        false,
  currentFilters:     [],
  sortField:          '',
  sortInverse:        false,
  paginationCurrent:  1,
  paginationPerPage:  10
};

export default function songsReducer (state = initialState, action) {
  const handler = ACTION_HANDLERS[action.type];

  return handler ? handler(state, action) : state;
}

