export const UI_SHOW_SNACKBAR      = 'UI_SHOW_SNACKBAR';
export const UI_HIDE_SNACKBAR      = 'UI_HIDE_SNACKBAR';
export const UI_TOGGLE_DRAWER_MENU = 'UI_TOGGLE_DRAWER_MENU';
export const UI_SHOW_DRAWER_MENU   = 'UI_SHOW_DRAWER_MENU';
export const UI_HIDE_DRAWER_MENU   = 'UI_HIDE_DRAWER_MENU';
export const UI_SHOW_MODAL         = 'UI_SHOW_MODAL';
export const UI_HIDE_MODAL         = 'UI_HIDE_MODAL';
export const UI_UPDATE_MODAL       = 'UI_UPDATE_MODAL';

export const MODAL_ADD_SONG        = 'MODAL_ADD_SONG';
export const MODAL_FILTER_SONGS    = 'MODAL_FILTER_SONGS';

export const INIT_VIEW_START       = 'INIT_VIEW_START';
export const INIT_VIEW_COMPLETE    = 'INIT_VIEW_COMPLETE';

// auth ui
export const HIDE_EMAIL_SIGN_IN_SUCCESS_MODAL          = 'HIDE_EMAIL_SIGN_IN_SUCCESS_MODAL';
export const HIDE_EMAIL_SIGN_IN_ERROR_MODAL            = 'HIDE_EMAIL_SIGN_IN_ERROR_MODAL';
export const HIDE_OAUTH_SIGN_IN_SUCCESS_MODAL          = 'HIDE_OAUTH_SIGN_IN_SUCCESS_MODAL';
export const HIDE_OAUTH_SIGN_IN_ERROR_MODAL            = 'HIDE_OAUTH_SIGN_IN_ERROR_MODAL';
export const HIDE_SIGN_OUT_ERROR_MODAL                 = 'HIDE_SIGN_OUT_ERROR_MODAL';
export const HIDE_SIGN_OUT_SUCCESS_MODAL               = 'HIDE_SIGN_OUT_SUCCESS_MODAL';
export const HIDE_EMAIL_SIGN_UP_SUCCESS_MODAL          = 'HIDE_EMAIL_SIGN_UP_SUCCESS_MODAL';
export const HIDE_EMAIL_SIGN_UP_ERROR_MODAL            = 'HIDE_EMAIL_SIGN_UP_ERROR_MODAL';
export const SHOW_FIRST_TIME_LOGIN_SUCCESS_MODAL       = 'SHOW_FIRST_TIME_LOGIN_SUCCESS_MODAL';
export const HIDE_FIRST_TIME_LOGIN_SUCCESS_MODAL       = 'HIDE_FIRST_TIME_LOGIN_SUCCESS_MODAL';
export const HIDE_PASSWORD_RESET_SUCCESS_MODAL         = 'HIDE_PASSWORD_RESET_SUCCESS_MODAL';
export const SHOW_PASSWORD_RESET_SUCCESS_MODAL         = 'SHOW_PASSWORD_RESET_SUCCESS_MODAL';
export const SHOW_FIRST_TIME_LOGIN_ERROR_MODAL         = 'SHOW_FIRST_TIME_LOGIN_ERROR_MODAL';
export const HIDE_FIRST_TIME_LOGIN_ERROR_MODAL         = 'HIDE_FIRST_TIME_LOGIN_ERROR_MODAL';
export const HIDE_PASSWORD_RESET_ERROR_MODAL           = 'HIDE_PASSWORD_RESET_ERROR_MODAL';
export const SHOW_PASSWORD_RESET_ERROR_MODAL           = 'SHOW_PASSWORD_RESET_ERROR_MODAL';
export const HIDE_REQUEST_PASSWORD_RESET_SUCCESS_MODAL = 'HIDE_REQUEST_PASSWORD_RESET_SUCCESS_MODAL';
export const HIDE_REQUEST_PASSWORD_RESET_ERROR_MODAL   = 'HIDE_REQUEST_PASSWORD_RESET_ERROR_MODAL';
export const HIDE_UPDATE_PASSWORD_SUCCESS_MODAL        = 'HIDE_UPDATE_PASSWORD_SUCCESS_MODAL';
export const HIDE_UPDATE_PASSWORD_ERROR_MODAL          = 'HIDE_UPDATE_PASSWORD_ERROR_MODAL';
export const HIDE_DESTROY_ACCOUNT_SUCCESS_MODAL        = 'HIDE_DESTROY_ACCOUNT_SUCCESS_MODAL';
export const HIDE_DESTROY_ACCOUNT_ERROR_MODAL          = 'HIDE_DESTROY_ACCOUNT_ERROR_MODAL';
