export const SNACKBAR_SHOW      = 'SNACKBAR_SHOW';
export const SNACKBAR_HIDE      = 'SNACKBAR_HIDE';
export const SNACKBAR_EXIT      = 'SNACKBAR_EXIT';

export const DRAWER_MENU_HIDE   = 'DRAWER_MENU_HIDE';
export const DRAWER_MENU_SHOW   = 'DRAWER_MENU_SHOW';
export const DRAWER_MENU_TOGGLE = 'DRAWER_MENU_TOGGLE';

export const MODAL_SHOW         = 'MODAL_SHOW';
export const MODAL_HIDE         = 'MODAL_HIDE';
export const MODAL_EXIT         = 'MODAL_EXIT';
export const MODAL_UPDATE       = 'MODAL_UPDATE';
export const MODAL_VARIANT_VIEW = 'MODAL_VIEW';
export const MODAL_VARIANT_ADD  = 'MODAL_ADD';
export const MODAL_VARIANT_EDIT = 'MODAL_EDIT';

export const SONG_MODAL         = 'SONG_MODAL';
export const FILTERS_MODAL      = 'FILTERS_MODAL';
export const PREVIEW_MODAL      = 'PREVIEW_MODAL';

export const FIELD_VIEW = 'FIELD_VIEW';
export const FIELD_ADD  = 'FIELD_ADD';
export const FIELD_EDIT = 'FIELD_EDIT';

export const INIT_VIEW_START    = 'INIT_VIEW_START';
export const INIT_VIEW_COMPLETE = 'INIT_VIEW_COMPLETE';
export const REFRESH_VIEW       = 'REFRESH_VIEW';

// auth ui
export const HIDE_EMAIL_SIGN_IN_SUCCESS_MODAL          = 'HIDE_EMAIL_SIGN_IN_SUCCESS_MODAL';
export const HIDE_EMAIL_SIGN_IN_ERROR_MODAL            = 'HIDE_EMAIL_SIGN_IN_ERROR_MODAL';
export const HIDE_OAUTH_SIGN_IN_SUCCESS_MODAL          = 'HIDE_OAUTH_SIGN_IN_SUCCESS_MODAL';
export const HIDE_OAUTH_SIGN_IN_ERROR_MODAL            = 'HIDE_OAUTH_SIGN_IN_ERROR_MODAL';
export const HIDE_SIGN_OUT_ERROR_MODAL                 = 'HIDE_SIGN_OUT_ERROR_MODAL';
export const HIDE_SIGN_OUT_SUCCESS_MODAL               = 'HIDE_SIGN_OUT_SUCCESS_MODAL';
export const HIDE_EMAIL_SIGN_UP_SUCCESS_MODAL          = 'HIDE_EMAIL_SIGN_UP_SUCCESS_MODAL';
export const HIDE_EMAIL_SIGN_UP_ERROR_MODAL            = 'HIDE_EMAIL_SIGN_UP_ERROR_MODAL';
export const SHOW_FIRST_TIME_LOGIN_SUCCESS_MODAL       = 'SHOW_FIRST_TIME_LOGIN_SUCCESS_MODAL';
export const HIDE_FIRST_TIME_LOGIN_SUCCESS_MODAL       = 'HIDE_FIRST_TIME_LOGIN_SUCCESS_MODAL';
export const HIDE_PASSWORD_RESET_SUCCESS_MODAL         = 'HIDE_PASSWORD_RESET_SUCCESS_MODAL';
export const SHOW_PASSWORD_RESET_SUCCESS_MODAL         = 'SHOW_PASSWORD_RESET_SUCCESS_MODAL';
export const SHOW_FIRST_TIME_LOGIN_ERROR_MODAL         = 'SHOW_FIRST_TIME_LOGIN_ERROR_MODAL';
export const HIDE_FIRST_TIME_LOGIN_ERROR_MODAL         = 'HIDE_FIRST_TIME_LOGIN_ERROR_MODAL';
export const HIDE_PASSWORD_RESET_ERROR_MODAL           = 'HIDE_PASSWORD_RESET_ERROR_MODAL';
export const SHOW_PASSWORD_RESET_ERROR_MODAL           = 'SHOW_PASSWORD_RESET_ERROR_MODAL';
export const HIDE_REQUEST_PASSWORD_RESET_SUCCESS_MODAL = 'HIDE_REQUEST_PASSWORD_RESET_SUCCESS_MODAL';
export const HIDE_REQUEST_PASSWORD_RESET_ERROR_MODAL   = 'HIDE_REQUEST_PASSWORD_RESET_ERROR_MODAL';
export const HIDE_UPDATE_PASSWORD_SUCCESS_MODAL        = 'HIDE_UPDATE_PASSWORD_SUCCESS_MODAL';
export const HIDE_UPDATE_PASSWORD_ERROR_MODAL          = 'HIDE_UPDATE_PASSWORD_ERROR_MODAL';
export const HIDE_DESTROY_ACCOUNT_SUCCESS_MODAL        = 'HIDE_DESTROY_ACCOUNT_SUCCESS_MODAL';
export const HIDE_DESTROY_ACCOUNT_ERROR_MODAL          = 'HIDE_DESTROY_ACCOUNT_ERROR_MODAL';
