export const FIELDS_EDIT_TAB      = 'V_FIELDS_EDIT_TAB';
export const FIELDS_SELECT_TAB    = 'V_FIELDS_SELECT_TAB';
export const FIELDS_DESELECT_TAB  = 'V_FIELDS_DESELECT_TAB';
export const FIELDS_PREVIEW_FIELD = 'V_FIELDS_PREVIEW_FIELD';
export const FIELDS_EDIT_FIELD    = 'V_FIELDS_EDIT_FIELD';
